### ISSUE TITLE
Where does the red background come from?

### ISSUE THREAD

**Issue by SSzretter** [PhantomAppDevelopment/pizza-app#10]
I have scoured the code and am not able to find the red background on most of the screens.  Can you tell me where this is set?

**Comment by agentphantom** [comment]
The global red background is declared in [this line](https://github.com/PhantomAppDevelopment/pizza-app/blob/master/src/PizzaApp.as#L14)

I will give a brief explanation of why it's there.

The default background of an AIR app is white. When you rotate the app and a Context Loss happens you will notice a brief flicker. This flicker is the same color as the global background.

What I do is to set the global background to the same as the dominant color of the app, this way when a context loss happens the flicker would be less noticeable.
