### ISSUE TITLE
addEventListener ou removeEventListener?

### ISSUE THREAD

**Issue by benkhachouch** [PhantomAppDevelopment/pizza-app#3]
in ChatroomsScreen:
private function accessTokenLoaded(event:flash.events.Event):void
		{
........
			event.currentTarget.addEventListener(flash.events.Event.COMPLETE, accessTokenLoaded);
}

**Comment by benkhachouch** [comment]
ok 
I just saw the update!

**Comment by agentphantom** [comment]
Thank you very much for reporting this!

I fixed the rest of eventListeners, it should also fix the other issue in ChatScreen.
