### ISSUE TITLE
Sometimes the sendButton  stuck.

### ISSUE THREAD

**Issue by benkhachouch** [PhantomAppDevelopment/pizza-app#5]
in ChatroomScreen

Sometimes the send button stuck.Why?

**Comment by agentphantom** [comment]
I guess it had something to do with the previous code. I just committed some fixes. Please try them and tell me if you still notice this issue.

**Comment by benkhachouch** [comment]
No problem il try it tomorrow .for me it is very late (Paris).Thanks.

**Comment by benkhachouch** [comment]
I test again the chatscreen

The problem has worsened
The send button does not react at all
This time nothing reacted.

**Comment by agentphantom** [comment]
Are you using my latest version or are you mixing it with your code?

I have tested it several times and it works perfectly for me.

**Comment by benkhachouch** [comment]
I do not understand. I just downloaded again your project like that and nothing reacted in chatscreen except the text entry

**Comment by agentphantom** [comment]
This is weird, I have just tried it again on my Android and PC, it works correctly on both.

If you are using Flash Builder try to clean the project, it might have cached some old code.

**Comment by benkhachouch** [comment]
Could you send me an apk for the test.
Thanks.

**Comment by agentphantom** [comment]
Sure, I will implement your code from the other issue and then I will create the APK.

**Comment by benkhachouch** [comment]
Thank you.

**Comment by agentphantom** [comment]
Here it is:

https://github.com/PhantomAppDevelopment/pizza-app/releases/download/1.0.1/PizzaApp.apk

**Comment by benkhachouch** [comment]
Thank you very much!

**Comment by benkhachouch** [comment]
the apk work very well

i think that my problem is with the database connection .I am verifying this.
