### ISSUE TITLE
I can't change displayname in settingsScreen

### ISSUE THREAD

**Issue by benkhachouch** [PhantomAppDevelopment/pizza-app#8]
I can't change display name in settingsScreen.
Thanks.

**Comment by agentphantom** [comment]
Which error does it output?

**Comment by benkhachouch** [comment]
No errer but display.why name dont changé.

**Comment by benkhachouch** [comment]
SSorry.
Display name don’t change. No error

**Comment by agentphantom** [comment]
Thank you for reporting it. I have fixed it in the latest commit.
